#First we prunt the list of students
puts "The students in my cohort at Makers Academy"
puts "------------"
puts "Dave"
puts "Eddie"
puts "Catharina"
puts "Igor"
puts "Marco"
puts "Lisa"
puts "Michiel"
puts "Jean"
puts "Nicola"
puts "Jennie"
puts "Iona"
puts "Nikesh"
puts "Chloe"
puts "Toan"
puts "Jamie"
puts "Peter"
puts "Talal"
puts "Charlie"
puts "Charlotte"
puts "Thomas"
puts "Zoe"
puts "Hannah"
puts "Joe"
puts "Alex"
puts "Jeremy"
#Finally, we print the total
print "Overall, we have "
#It's important that print() doesn't add new line characters
print 25
puts " great students"